/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Country;

import Business.Country.Country;
import Business.EcoSystem.EcoSystem;
import Business.EcoSystem.EcoSystemRepresentative;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Manish
 */
public class CountryHeadWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form CountryHeadWorkAreaPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Country country;
    private EcoSystem system;
    private EcoSystemRepresentative unitedNationsRepresentative;
    
    public CountryHeadWorkAreaPanel(JPanel userProcessContainer, UserAccount account, Country country, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.country = country;
        this.system = system;       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        manageDepartmentJButton = new javax.swing.JButton();
        manageUNRepresentativeJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Country Head Work Area");

        jLabel2.setText("Country:");

        jLabel3.setText("<Value>");

        manageDepartmentJButton.setText("Manage Departments");
        manageDepartmentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDepartmentJButtonActionPerformed(evt);
            }
        });

        manageUNRepresentativeJButton.setText("Manage UN Representative");
        manageUNRepresentativeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUNRepresentativeJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageUNRepresentativeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageDepartmentJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(61, 61, 61)
                .addComponent(manageUNRepresentativeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(manageDepartmentJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageUNRepresentativeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUNRepresentativeJButtonActionPerformed
        // TODO add your handling code here:
        ManageUNRepresentativeJPanel manageUNRepresentativeJPanel =  new ManageUNRepresentativeJPanel(userProcessContainer,country);
        userProcessContainer.add("ManageUNRepresentativeJPanel", manageUNRepresentativeJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageUNRepresentativeJButtonActionPerformed

    private void manageDepartmentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDepartmentJButtonActionPerformed
        // TODO add your handling code here:
        ManageDepartmentJPanel manageDepartmentJPanel =  new ManageDepartmentJPanel();
        userProcessContainer.add("ManageDepartmentJPanel", manageDepartmentJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageDepartmentJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton manageDepartmentJButton;
    private javax.swing.JButton manageUNRepresentativeJButton;
    // End of variables declaration//GEN-END:variables
}
