/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HealthDepartment;

/**
 *
 * @author Manish Patil
 */
public class UpdateHealthDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateHealthDetailsJPanel
     */
    public UpdateHealthDetailsJPanel() {
        initComponents();
        
        
        populateRefugeeTable();
    }

    public void populateRefugeeTable(){
    
    
}
    /**()
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        refugeeListTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        addVitalSignButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        firstNameTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lastNameTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        temperatureTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pulseTxtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CholastrolNCEP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cholestrolLDLTxtField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cholestrolHDLTxtField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lowBloodPressureTxtField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        highBloodPressureTxtField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();

        jLabel9.setText("First Name:");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        refugeeListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Age", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(refugeeListTable);
        if (refugeeListTable.getColumnModel().getColumnCount() > 0) {
            refugeeListTable.getColumnModel().getColumn(0).setResizable(false);
            refugeeListTable.getColumnModel().getColumn(1).setResizable(false);
            refugeeListTable.getColumnModel().getColumn(2).setResizable(false);
            refugeeListTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setText("List of Refugees:");

        backButton.setText("<< Back");

        addVitalSignButton.setText("Add Vital Signs");
        addVitalSignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVitalSignButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("First Name:");

        firstNameTxtField.setEnabled(false);
        firstNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTxtFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Last Name:");

        lastNameTxtField.setEnabled(false);
        lastNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTxtFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Temperature:");

        temperatureTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperatureTxtFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Pulse:");

        pulseTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulseTxtFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Cholestrol NCEP: ");

        CholastrolNCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CholastrolNCEPActionPerformed(evt);
            }
        });

        jLabel7.setText("Cholestrol LDL:");

        cholestrolLDLTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cholestrolLDLTxtFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Cholestrol HDL:");

        cholestrolHDLTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cholestrolHDLTxtFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Blood Pressure Low:");

        lowBloodPressureTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowBloodPressureTxtFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Blood Pressure High:");

        highBloodPressureTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highBloodPressureTxtFieldActionPerformed(evt);
            }
        });

        updateButton.setText("Update");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(35, 35, 35)
                                .addComponent(lastNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addVitalSignButton)
                                    .addComponent(firstNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(35, 35, 35)
                                .addComponent(temperatureTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(35, 35, 35)
                                .addComponent(pulseTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(35, 35, 35)
                                .addComponent(CholastrolNCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(35, 35, 35)
                                .addComponent(cholestrolLDLTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(35, 35, 35)
                                .addComponent(cholestrolHDLTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(35, 35, 35)
                                .addComponent(lowBloodPressureTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(updateButton))
                                    .addComponent(highBloodPressureTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addVitalSignButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(temperatureTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pulseTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CholastrolNCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cholestrolLDLTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cholestrolHDLTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lowBloodPressureTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(highBloodPressureTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addVitalSignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVitalSignButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addVitalSignButtonActionPerformed

    private void firstNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTxtFieldActionPerformed

    private void lastNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTxtFieldActionPerformed

    private void temperatureTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperatureTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temperatureTxtFieldActionPerformed

    private void pulseTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulseTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pulseTxtFieldActionPerformed

    private void CholastrolNCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CholastrolNCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CholastrolNCEPActionPerformed

    private void cholestrolLDLTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cholestrolLDLTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cholestrolLDLTxtFieldActionPerformed

    private void cholestrolHDLTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cholestrolHDLTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cholestrolHDLTxtFieldActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void lowBloodPressureTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowBloodPressureTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lowBloodPressureTxtFieldActionPerformed

    private void highBloodPressureTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highBloodPressureTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highBloodPressureTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CholastrolNCEP;
    private javax.swing.JButton addVitalSignButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField cholestrolHDLTxtField;
    private javax.swing.JTextField cholestrolLDLTxtField;
    private javax.swing.JTextField firstNameTxtField;
    private javax.swing.JTextField highBloodPressureTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField lastNameTxtField;
    private javax.swing.JTextField lowBloodPressureTxtField;
    private javax.swing.JTextField pulseTxtField;
    private javax.swing.JTable refugeeListTable;
    private javax.swing.JTextField temperatureTxtField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
