/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package userinterface.AdministrativeRole;

import Business.Continent.Continent;
import Business.Country.Country;
import Business.Country.CountryDirectory;
import Business.EcoSystem.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;


/**
 *
 * @author  
 */
public class SystemAdminWorkAreaJPanel extends JPanel {
    
    JPanel userProcessContainer;
    Country country;
    CountryDirectory countryDirectory;
    EcoSystem unitedNations;
    
    Continent continents;
    /** Creates new form AdminWorkAreaJPanel
     * @param userProcessContainer
     * @param country */
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer) {
        
        initComponents();
        this.userProcessContainer = userProcessContainer;
        
        countryDirectory = new CountryDirectory();
        for(Continent continent : EcoSystem.getInstance().
                getContinentDirectory().getContinents()) {
            for(Country country : continent.getCountryDirectory().getCountryList()) {
                countryDirectory.getCountryList().add(country);
            }
        }
        //this.countryDirectory = unitedNations.getContinentList()
    /*
        this.country = country;
        this.continents = continents;
        this.countryDirectory = countryDirectory;
    */
    
    //    valueLabel.setText(country.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userJButton = new javax.swing.JButton();
        createDepartmentJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        manageUNHeadButton = new javax.swing.JButton();
        createHeadJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Aminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        userJButton.setText("Manage User");
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });
        add(userJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 210, 30));

        createDepartmentJButton.setText("Create Department");
        createDepartmentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDepartmentJButtonActionPerformed(evt);
            }
        });
        add(createDepartmentJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 210, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("United Nations: ");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 170, 30));

        manageUNHeadButton.setText("Manage UN Head");
        manageUNHeadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUNHeadButtonActionPerformed(evt);
            }
        });
        add(manageUNHeadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 210, 40));

        createHeadJButton.setText("Create Head");
        createHeadJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createHeadJButtonActionPerformed(evt);
            }
        });
        add(createHeadJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 210, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, country);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userJButtonActionPerformed

    private void createHeadJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createHeadJButtonActionPerformed
        CreateHeadJPanel manageCountryHeadJPanel = 
                new CreateHeadJPanel(userProcessContainer);
                
        userProcessContainer.add("manageCountryHeadJPanel", manageCountryHeadJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createHeadJButtonActionPerformed

    private void manageUNHeadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUNHeadButtonActionPerformed
        // TODO add your handling code here:
        ManageUNJPanel manageUNJPanel = new ManageUNJPanel(userProcessContainer);
        userProcessContainer.add("ManageUNJPanel", manageUNJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageUNHeadButtonActionPerformed

    private void createDepartmentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDepartmentJButtonActionPerformed

        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(
                userProcessContainer);
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_createDepartmentJButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createDepartmentJButton;
    private javax.swing.JButton createHeadJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageUNHeadButton;
    private javax.swing.JButton userJButton;
    // End of variables declaration//GEN-END:variables
    
}
