/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UNRepresentativeRole;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Manish
 */
public class UNRepresentativeWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UNRepresentativeWorkAreaJPanel
     */
    JPanel userProcessContainer;
    public UNRepresentativeWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageRequestJButton = new javax.swing.JButton();
        manageCitizenJButton = new javax.swing.JButton();
        createRefugeeRequestButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("UN Representative Work Area");

        manageRequestJButton.setText("Manage Request");
        manageRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRequestJButtonActionPerformed(evt);
            }
        });

        manageCitizenJButton.setText("Manage Citizens");
        manageCitizenJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCitizenJButtonActionPerformed(evt);
            }
        });

        createRefugeeRequestButton.setText("Create Refugee Request");
        createRefugeeRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRefugeeRequestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1)
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createRefugeeRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageCitizenJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageRequestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(225, 225, 225))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addComponent(manageCitizenJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(manageRequestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(createRefugeeRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRequestJButtonActionPerformed
        // TODO add your handling code here:
        ManageRequestsJPanel manageRequestsJPanel =  new ManageRequestsJPanel();
        userProcessContainer.add("ManageRequestsJPanel", manageRequestsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageRequestJButtonActionPerformed

    private void manageCitizenJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCitizenJButtonActionPerformed
        ManageCitizenJPanel manageCitizenJPanel =  new ManageCitizenJPanel();
        userProcessContainer.add("ManageCitizenJPanel", manageCitizenJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCitizenJButtonActionPerformed

    private void createRefugeeRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRefugeeRequestButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createRefugeeRequestButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createRefugeeRequestButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageCitizenJButton;
    private javax.swing.JButton manageRequestJButton;
    // End of variables declaration//GEN-END:variables
}
